# Generated by Django 4.1.5 on 2023-01-12 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorProduct', models.CharField(max_length=30, verbose_name='Цвет продукта')),
                ('sizeProduct', models.CharField(max_length=10, verbose_name='Размер продукта')),
                ('countProduct', models.IntegerField(max_length=15)),
                ('priceProduct', models.IntegerField()),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
