# Generated by Django 4.1.5 on 2023-01-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='priceProduct',
            field=models.IntegerField(default=0),
        ),
    ]
