# Generated by Django 4.1.5 on 2023-01-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_basket_priceproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзину', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterField(
            model_name='basket',
            name='countProduct',
            field=models.IntegerField(default=1),
        ),
    ]
